# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactNativeApp

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  target 'reactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
